/* Name: Harshali Mahesh Mugutrao
 * UTA ID: 1001747263
 */

package Client;  //package that contains all files related to Client side processing java.awt.EventQueue;

/* packages required for Directory Watching and Input Output*/
import javax.swing.*;
import java.awt.event.*;
import java.io.*;
import java.awt.*;

public class ClientWindow {

	private JFrame frame;      //variable for GUI Window
	private JTextField textField; //Text field to input user name

	/* Launch the application */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {      //To update GUI at the end
			public void run() {
				try {
					ClientWindow window = new ClientWindow();   //Create instance of our class to set properties
					window.frame.setVisible(true);              //User should see the window, hence setVisible property is set to true
				}
				catch (Exception e) {
					e.printStackTrace();                       //print any errors
				}
			}
		});
	}

	/*Create the application.*/
	public ClientWindow() {
		initialize();
	}

	/*Initialize the contents of the frame.
	 This is default code generated by using Java Window Application file */
	
	private void initialize() {
		frame = new JFrame();
		frame.setBounds(100, 100, 606, 440);                    //sets window size
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);  //To close window after user clicks on the close(i.e. X) sign
		frame.getContentPane().setLayout(new FlowLayout(FlowLayout.CENTER,5,5));                 //to set position of window
		
		JLabel labelSetName = new JLabel("   Please enter a username");  //set label
		labelSetName.setFont(new Font("Trebuchet MS", Font.PLAIN, 15));  // set font of label
		labelSetName.setBounds(26, 13, 197, 61);                         //set label position
		frame.getContentPane().add(labelSetName);                        //add label on window
		
		textField = new JTextField();                          //Declaring text field to input user name
		textField.setBounds(248, 25, 134, 29);                // set position for text field
		textField.setColumns(10);                             //set height of text field
		frame.getContentPane().add(textField);                //add text field in window
		
		JButton btnSet = new JButton("Set");                 //Declared button to set username
		btnSet.setBackground(Color.WHITE);                   //set button color
		btnSet.setBounds(437, 18, 112, 36);                 //set button position
		frame.getContentPane().add(btnSet);                 //add button in window
		
		JTextArea textArea = new JTextArea(16,40);                        //Declared textArea to print messages
		textArea.setFont(new Font("Monospaced", Font.PLAIN, 15));   //set text area font
		textArea.setLineWrap(true);                                 //styling for text area
		textArea.setWrapStyleWord(true);
		textArea.setEditable(false);                               //editable=false, as we do not allow user to write in text area
		textArea.setBounds(12, 67, 564, 313);                      //set boundary for text area
		frame.getContentPane().add(textArea);                      //add text area to the window
		
		/*Redirected console content to text area for printing
		  https://stackoverflow.com/questions/5107629/how-to-redirect-console-content-to-a-textarea-in-java
		 */
		//PrintStream printStream = new PrintStream(new CustomOutputStreamClient(textArea));
		//System.setOut(printStream);
		//System.setErr(printStream);
		
		/* On click of button-Set, control goes to Client class for validation and processing 
		   https://stackoverflow.com/questions/35094602/java-app-cant-be-closed-even-close-on-exit-tcp-server
		 */
        btnSet.addActionListener(new ActionListener() {
	    @Override
	    public void actionPerformed(ActionEvent event) {
	    	
	    	String uname=textField.getText();   //Get user name from user
	        //System.out.println("Username is set to " + uname);
			
			try {
				Client c1=new Client();   //created instance of Client class
				Client.main(uname);       //Accessing Client class
			} 
			
			catch (Exception e) {
				// print errors (if any)
				e.printStackTrace();
			}
	        
	    }
	});
	}
}
